# Generic: UNESCO heritage sites, national parks, and protected areas.
# {COUNTRY_QID} {LANG} {FILTER} {LIMIT}
SELECT DISTINCT ?item ?itemLabel ?itemDescription ?type ?typeLabel ?coord WHERE {
  VALUES ?country { wd:{COUNTRY_QID} }
  { ?item wdt:P31 wd:Q9259 . }        # UNESCO World Heritage
    UNION
  { ?item wdt:P31 wd:Q916333 . }       # National park
    UNION
  { ?item wdt:P17 ?country . ?item wdt:P31 wd:Q570116 . }  # Intangible heritage
    UNION
  { ?item wdt:P17 ?country . ?item wdt:P31 wd:Q498990 . }  # Historic district
  OPTIONAL { ?item wdt:P625 ?coord . }
  {FILTER}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "{LANG},en" . }
}
LIMIT {LIMIT}
